// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resort.Infrastructure.Data;

#nullable disable

namespace Resort.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250116135415_add_VillaTable")]
    partial class add_VillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Resort.Domain.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SquareFeet")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No more prons for that Villa",
                            ImgURL = "https://placehold.co/600X400",
                            Name = "Normal Villa",
                            Occupancy = 4,
                            Price = 1000.0,
                            SquareFeet = 500
                        },
                        new
                        {
                            Id = 2,
                            Description = " more advantages for that Villa",
                            ImgURL = "https://placehold.co/600X401",
                            Name = "Royal Villa",
                            Occupancy = 6,
                            Price = 2000.0,
                            SquareFeet = 600
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Best Villa at all",
                            ImgURL = "https://placehold.co/600X402",
                            Name = "Luxury Villa",
                            Occupancy = 4,
                            Price = 3000.0,
                            SquareFeet = 900
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
